---
title: "Testing File"
author: "Armina Parvaresh Rizi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
house_rc <- read.csv("../data/H118_rollcalls_CLEANSED.csv")
senate_rc <- read.csv("../data/S118_rollcalls_CLEANSED.csv")

head(house_rc)
head(senate_rc)

house_bills <- house_rc$rollnumber
senate_bills <- senate_rc$rollnumber
print(house_bills)
```

```{r}
house_votes <- read.csv("../data/H118_votes.csv")
senate_votes <- read.csv("../data/S118_votes.csv")

head(house_votes)
head(senate_votes)

# https://www.statology.org/r-filter-in/
house_filtered_votes <- house_votes[house_votes$rollnumber %in% house_bills, ]
senate_filtered_votes <- senate_votes[senate_votes$rollnumber %in% senate_bills, ]

# set cast 1,2,3 as yay, 4,5,6 as nay, and 0,7,8,9 as N/A (or abstain)
# we should never get to anywhere outside of 0-9 for cast code, but using NA for error handling
house_filtered_votes$vote_label <- with(house_filtered_votes, ifelse(cast_code %in% c(1, 2, 3), 1,
                          ifelse(cast_code %in% c(4, 5, 6), -1,
                          ifelse(cast_code %in% c(0, 7, 8, 9), 0, NA))))

senate_filtered_votes$vote_label <- with(senate_filtered_votes, ifelse(cast_code %in% c(1, 2, 3), 1,
                          ifelse(cast_code %in% c(4, 5, 6), -1,
                          ifelse(cast_code %in% c(0, 7, 8, 9), 0, NA))))
```
making sure that all of the bills are filtered (reduced filter rows)
```{r}
print(nrow(senate_filtered_votes))
print(nrow(senate_votes))

print(nrow(house_filtered_votes))
print(nrow(house_votes))
```

```{r}
house_members <- read.csv("../data/H118_votes.csv")
senate_members <- read.csv("../data/S118_votes.csv")

# grab relevant icpsrs -- TODO: might remove this in the future but idk if we should just get the relevant members (sounds better for computation)
house_icpsr <- house_filtered_votes$icpsr
senate_icpsr <- senate_filtered_votes$icpsr

# head(house_members)
house_filtered_members <- house_members[house_members$rollnumber %in% house_bills, ]
senate_filtered_members <- senate_members[senate_members$rollnumber %in% senate_bills, ]
```

```{r}
# these should match the numbers from above
nrow(house_filtered_members)
nrow(senate_filtered_members)
```

## making the matrix
```{r matrix}
# we assume that the vote df has icpsr, rollnumber, and the vote label we assigned 
build_user_item_matrix <- function(votes_df) {
  users <- sort(unique(votes_df$icpsr))
  # items = bills
  bills <- sort(unique(votes_df$rollnumber))

  # initialize matrix of 0s
  mat <- matrix(0,
                nrow = length(users),
                ncol = length(bills),
                dimnames = list(users, bills))

  # fill matrix
  for (i in seq_len(nrow(votes_df))) {
    u <- votes_df$icpsr[i]
    b <- votes_df$rollnumber[i]
    v <- votes_df$vote_label[i]
    
    # place vote into correct cell
    mat[as.character(u), as.character(b)] <- v
  }

  return(mat)
}
```

```{r}
house_matrix <- build_user_item_matrix(house_filtered_votes)
senate_matrix <- build_user_item_matrix(senate_filtered_votes)

# sanity checking
print(length(unique(house_filtered_members$icpsr)))
print(length(unique(house_filtered_votes$rollnumber)))
dim(house_matrix)

print(length(unique(senate_filtered_members$icpsr)))
print(length(unique(senate_filtered_votes$rollnumber)))
dim(senate_matrix)
```

```{r}
house_matrix[1:5, 1:5]
```

```{r}
senate_matrix[1:5, 1:5]
```

```{r}
cosine_similarity <- function(u1, u2) {
  dot_product <- sum(u1 * u2)
  u1_magnitude <- sqrt(sum(u1 * u1))
  u2_magnitude <- sqrt(sum(u2 * u2))
  sim <- dot_product / (u1_magnitude * u2_magnitude)
  return (sim)
}

build_cos_matrix <- function(votes_mat) {
  n <- ncol(votes_mat)
  sim <- matrix(0, n, n, dimnames = list(colnames(votes_mat), colnames(votes_mat)))
  for (i in 1:n) {
    for (j in i:n) {
      s <- cosine_similarity(votes_mat[, i], votes_mat[, j])
      sim[i, j] <- s
      sim[j, i] <- s
    }
  }
  sim
}

sim_scores <- build_cos_matrix(cbind(drg, st1, st2, st3, st4))
sim_scores
```

```{r}
library(ggplot2)

bill_id <- 231

# Get bill data
bill_data <- house_votes[house_votes$rollnumber == bill_id, ]
bill_point <- c(bill_data$nominate_mid_1, bill_data$nominate_mid_2)


```

```{r}
house_mat <- read.csv("house_cf_118.csv", row.names = 1, check.names = FALSE)
# Get ICPSR IDs of yea (1) and nay (-1) voters
yea_ids <- c()
nay_ids <- c()
if (as.character(bill_id) %in% colnames(house_mat)) {
  yea_ids <- rownames(house_mat)[house_mat[, as.character(bill_id)] == 1]
  nay_ids <- rownames(house_mat)[house_mat[, as.character(bill_id)] == -1]
}
# Add a column to indicate vote type
house_members <- house_votes %>%
  mutate(vote = case_when(
    icpsr %in% yea_ids ~ "Yea",
    icpsr %in% nay_ids ~ "Nay",
    TRUE ~ "Other"
  ))

# Plot
ggplot(house_members, aes(x = nominate_dim1, y = nominate_dim2)) +
  geom_point(aes(color = vote), alpha = 0.7) +
  scale_color_manual(values = c("Yea" = "green", "Nay" = "red", "Other" = "lightgray")) +
  geom_point(aes(x = bill_point[1], y = bill_point[2]), color = "blue", shape = 8, size = 5) +
  labs(
    x = "Nominate Dimension 1",
    y = "Nominate Dimension 2",
    title = paste("Ideological Space with Bill", bill_id, "Location"),
    color = "Vote"
  ) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  theme_minimal()
```


